### ISSUE TITLE
Adding license to package.json

### ISSUE THREAD

**Issue by amarzavery** [joebain/args.js#19]
@joebain - I loved the work you have done. I have been looking for a library like this for some time. 
My team at Microsoft is working on a code generator named [AutoRest](https://github.com/Azure/autorest) that consumes a [Swagger spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md) and generates client side libraries for Azure SDK in NodeJS, C#, Java and Ruby. I wanted to use args.js for validating method parameters. The [licenses field](https://docs.npmjs.com/files/package.json#license) in package.json is missing. Can you please update it?

**Comment by joebain** [comment]
I've just added the license info - MIT. Good you hear you find it useful.

**Comment by amarzavery** [comment]
Thank you.

Thanks,
Amar Zavery

On Nov 24, 2015, at 1:07 AM, "Joe Bain" <notifications@github.com<mailto:notifications@github.com>> wrote:


I've just added the license info - MIT. Good you hear you find it useful.

-
