### ISSUE TITLE
Is it possible to have an optional argument group?

### ISSUE THREAD

**Issue by vjpr** [joebain/args.js#20]
E.g. `function(string | object, [object], [string | object])`

**Comment by joebain** [comment]
I'm not sure I understand the proposal. Can you give an example?

**Comment by moscartong** [comment]
@joebain currently in ArgsJS, argument group is required. You must provide one of the arguments in the group.

**Comment by joebain** [comment]
I see. It would be a bit of a change to the code, and I'm not sure how the syntax would work either. If you think you can implement it I'm happy to take a PR. I may be able to take a look at it myself on the weekend, but no promises I'm afraid.
