### ISSUE TITLE
instanceof giving false negatives for arrays

### ISSUE THREAD

**Issue by dmfay** [joebain/args.js#22]
From https://github.com/robconery/massive-js/issues/173

I'm afraid it's a something of an ordeal to set up the conditions necessary to reproduce the problem -- install Postgres and Massive, set up the test database, open the REPL from the test directory, and invoke `db.productByName(['Product 1', 'Product 2'], console.log);` -- but switching from `instanceof` to `Array.isArray` for array detection seems to resolve it completely.

**Comment by joebain** [comment]
Seems like this has to do with Arrays being constructed in different contexts - http://web.mit.edu/jwalden/www/isArray.html

`Array.isArray` is ES5 only though - I would rather not restrict to that. Can you incorporate the polyfill (like the one here - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) or a fallback to the old logic when `Array.isArray` is not available?

**Comment by dmfay** [comment]
Sure, I've added the polyfill.
