### ISSUE TITLE
Args.Optional + _check not throwing exception

### ISSUE THREAD

**Issue by moscartong** [joebain/args.js#24]
The following code:

```javascript
function foo() {
    let args = Args([
        {url:Args.STRING|Args.Optional, _check:(url) => url.match(/^\w+\:\/\//)}
    ], arguments);
    ...
}
```

expect `foo('bar')` to throw an exception because _check returns null (not true).
actually no exception is throw and args.url === null.

But if url is an Args.Required, then the code works as expected.

**Comment by joebain** [comment]
This is the correct behaviour I'm afraid. The `_check` function is supposed to provide additional logic for argument matching, rather than act as a input filter in the way you describe. If you can't use `Required` I would suggest you do your url check separately and throw an exception yourself.

**Comment by moscartong** [comment]
I see. I will move the check logic somewhere else and throw my exception there then. Thanks for the quick reply👍
