### ISSUE TITLE
Objects in named arguments in argument group not working as expected

### ISSUE THREAD

**Issue by irvinlim** [joebain/args.js#27]
I've been trying to do the following:

```
function getAccessToken() {
    const args = Args([
        // Argument group, any one of the 3 parameters can be used.
        [
            { userId:        Args.STRING },
            { accessToken:   Args.STRING },
            { user:          Args.OBJECT },
        ],
    ], arguments);

    console.log(args);
}

const userObject = { _id: 123, name: "User Name" };
getAccessToken({ user: userObject });
```

I would expect the arguments to be:
```
{ user: { _id: 123, name: 'User Name' } }
```

But instead I'm getting:
```
{ user: { user: { _id: 123, name: 'User Name' } } }
```

Indeed, not using an argument group returns the correct response. I would believe it is because by using named arguments, `arguments[0]` is an object which is then parsed as a `user` argument (in the argument group), hence resulting in the incorrect response.

Is this a bug, or is there an option to make args.js only use named arguments, to avoid this problem? Thank you very much.

**Comment by joebain** [comment]
I think you are right, that it matches the whole object as the user object, without looking "inside" it for a named property. The reason is because argument groups do not work with named arguments, they are really designed for grabbing positional arguments. If you have some optional named arguments then you can list them outside of a group and specify them as optional using `Args.Optional`.

Perhaps I don't fully understand the use case though? Are you using Args.js to ensure that at least one of arguments in the group is passed, so you want an error otherwise?

**Comment by irvinlim** [comment]
Thanks for the reply! Yes, I was intending to use argument groups for that purpose, although *not* using argument groups would also suffice for me, I can do a simple check after receiving the arguments from `Args()`.

I just thought that I would like to point out a potential bug if my use case was the intended usage - apparently not. Otherwise, it would also be good if there was a parameter for preference for named or non-named arguments, or both, if it could be less ambiguous for the usage.

**Comment by joebain** [comment]
It would be a nice feature I think. We now have two open issues which are basically argument group features, so I'll see if I can put some work in to get them done. Watch this space :)

**Comment by irvinlim** [comment]
Great, thanks! :+1:

**Comment by joebain** [comment]
I've been thinking about how we can support this feature, but unfortunately I don't believe we can without introducing ambiguity. In this case the user object and the container both equivalently match `Args.OBJECT` and I can't see how we can tell them apart reliably.

Perhaps in this situation you could do this:

```
function getAccessToken() {
    const args = Args([
        // Argument group, any one of the 3 parameters can be used.
        [
            { userId:        Args.STRING },
            { accessToken:   Args.STRING },
            { user:          Args.OBJECT },
        ],
    ], arguments);

    console.log(args);
}

const userObject = { _id: 123, name: "User Name" };
getAccessToken(userObject);
```

I.e. pass the user object in without wrapping it in another object, this will throw an error if it is (or and id or an access token) are not present.

**Comment by irvinlim** [comment]
Hmm... That would work, unless you actually require to use named arguments. The example I provided is rather simplified. Either way, I am fine with simply just not using argument groups, and perform validation separately.

Thank you for your time anyway!
